// Navigation component actions
export const UPDATE_NAVIGATION_LOGIN_SUCCESS = "UPDATE_NAVIGATION_LOGIN_SUCCESS";
export const UPDATE_NAVIGATION_LOGOUT_SUCCESS = "UPDATE_NAVIGATION_LOGOUT_SUCCESS";

// User profile component actions
export const UPDATE_PROFILE_DATA_SUCCESS = "UPDATE_PROFILE_DATA_SUCCESS";
export const UPDATE_PROFILE_DATA_FAIL = "UPDATE_PROFILE_DATA_FAIL";

// Recommended section component
export const UPDATE_RECOMMENDED_SECTION_SUCCESS = "UPDATE_RECOMMENDED_SECTION_SUCCESS";
export const UPDATE_RECOMMENDED_SECTION_FAIL = "UPDATE_RECOMMENDED_SECTION_FAIL";

// Popular section component actions
export const UPDATE_POPULAR_SUCCESS = "UPDATE_POPULAR_SUCCESS";
export const UPDATE_POPULAR_FAIL = "UPDATE_POPULAR_FAIL";

// Comment component actions
export const UPDATE_COMMENTS_SUCCESS = "UPDATE_COMMENTS_SUCCESS";
export const UPDATE_COMMENTS_INSERT = "UPDATE_COMMENTS_INSERT";
export const UPDATE_COMMENTS_FAIL = "UPDATE_COMMENTS_FAIL";

// Aritcle component actions
export const UPDATE_ARTICLES_SUCCESS = "UPDATE_ARTICLES_SUCCESS";
export const UPDATE_ARTICLES_FAIL = "UPDATE_ARTICLES_FAIL";

// Carousel component actions
export const UPDATE_CAROUSEL_SUCCESS = "UPDATE_CAROUSEL_SUCCESS";
export const UPDATE_CAROUSEL_FAIL = "UPDATE_CAROUSEL_FAIL";

// Search function actions (Navigation bar)
export const UPDATE_SEARCH_RESULTS_FAIL = "UPDATE_SEARCH_RESULTS_FAIL";
export const UPDATE_SEARCH_RESULTS_SUCCESS = "UPDATE_SEARCH_RESULTS_SUCCESS";

// Login/Logout component actions
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";